"""
research_agent/ops/package.py -- build the archive a reviewer receives (D-190).

Purpose:
    Produce a distributable zip of this repository from an EXPLICIT
    include/exclude policy, then verify the file that was actually
    written -- so "what a reviewer receives" and "what passed the gate"
    are the same bytes.

WHY THIS EXISTS AS A COMMAND AND NOT AS A README PARAGRAPH. It already
was a README paragraph. README's Packaging section carried a PowerShell
snippet and a bash snippet, an exclude list, and the verification command
to run afterwards -- and an archive of this project still shipped with
`.env` in it, carrying a live Mistral key, a live cloud-fallback key, a
Langfuse pk-/sk- pair, an OpenSearch password and a Postgres DSN. The
same archive carried `logs/`, `tmp/` and 21 `__pycache__` directories;
161 of its 373 files were compiled bytecode.

That is the identical failure mode `scripts/sanity.py` exists for, one
step later in the process: a correct procedure that a person has to
remember, at exactly the moment they are in a hurry. D-158 wrote the
procedure down. This runs it.

    THE ARCHIVE IS NOT THE REPOSITORY, AND `.gitignore` DOES NOT HELP
    HERE. `.env` is correctly gitignored, so it can never reach a clone,
    a `git archive` or a push. A zip of the working directory carries it
    anyway. And `git archive HEAD` is not the answer either, because
    `internal/` is deliberately IN the archive and deliberately OUT of
    git (see README's document map) -- which is precisely why an
    explicit list, applied to the working tree, is the only mechanism
    that can be correct here.

WHAT IT DELIBERATELY DOES NOT DO:
    - It does NOT rotate anything. If a secret has already gone out, a
      smaller zip does not call it back; the remedy is to rotate every
      credential that was in it, and this command says so when it finds
      one rather than implying the problem is now handled.
    - It does NOT lint or test. `scripts/sanity.py` is that gate and runs
      first; this one answers the different question of whether the
      artifact matches the tree that passed it. Chaining them here would
      make one failure look like the other.
    - It does NOT know what is secret in general. The scan below is a
      backstop against a known, narrow set of shapes, not a secret
      scanner -- see `scan_text`'s own docstring for what it can and
      cannot see.

Usage:
    python scripts/package.py                 # -> ../research-agent.zip
    python scripts/package.py --out dist/ra.zip
    python scripts/package.py --dry-run       # list what would go in
    python scripts/package.py --list-excluded # and what would not

Exit codes:
    0  archive written and verified
    1  refused: a forbidden path or a credential-shaped value was found
    2  not run from a checkout (there is no tree to package)
"""

import argparse
import fnmatch
import os
import pathlib
import re
import sys
import zipfile

from research_agent.ops._paths import repo_root

REPO_ROOT = repo_root()

# Paths that must NEVER enter the archive, as glob patterns matched
# against each file's POSIX-style path relative to the repo root, and
# against every one of its parent directories.
#
# ORDERED BY WHY, because the reasons are not the same and a future
# editor should not treat them as one list:
#
#   secrets       .env is the one that actually shipped. There is no
#                 second copy of this rule anywhere -- .gitignore governs
#                 git, and this governs the archive.
#   environments  a .venv is machine-specific, enormous, and can itself
#                 contain credentials in a config file.
#   run artifacts logs/ and tmp/ hold real queries, real retrieved
#                 content and real telemetry from whoever ran last. They
#                 are also where a debug trace writes prompts verbatim.
#   build output  regenerated by a build; shipping it invites a consumer
#                 to run a stale wheel.
#   caches        bytecode and tool caches are noise that made 161 of one
#                 archive's 373 files meaningless.
#
# `internal/` is deliberately ABSENT from this list -- see the module
# docstring. `sample_data/`, `design/` and `.github/` are likewise meant
# to travel.
EXCLUDE_PATTERNS = (
    # secrets
    ".env",
    ".env.*",
    "!.env.example",          # negation, handled in is_excluded below
    "*.pem",
    "*.key",
    "id_rsa*",
    # environments
    ".venv",
    "venv",
    "env",
    "ENV",
    # run artifacts
    "logs",
    "tmp",
    "run.log",
    # build output
    "build",
    "dist",
    "*.egg-info",
    # caches and editor/OS droppings
    "__pycache__",
    "*.pyc",
    "*.pyo",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    ".coverage",
    ".coverage.*",
    ".git",
    ".idea",
    ".vscode",
    ".DS_Store",
    "Thumbs.db",
    "node_modules",
)

# Kept out of the pattern loop because it is a NEGATION, not an
# exclusion: `.env.*` would otherwise take `.env.example` with it, and
# `.env.example` is the one file in that family that must ship.
KEEP_ANYWAY = (".env.example",)

# ---------------------------------------------------------------------------
# The credential backstop.
#
# NOT A SECRET SCANNER, and the distinction matters because calling it
# one would invite trust it cannot carry. It looks for one shape: an
# assignment whose NAME says credential and whose VALUE is long enough to
# be one and is not a recognisable placeholder. That catches the case
# this repo actually needs catching -- a real key pasted into a document,
# a .env copied to .env.bak, a DSN left in a runbook -- and it will miss
# a credential that does not look like an assignment.
#
# It never prints the value it found. A tool whose failure output leaks
# the secret it is protecting has moved the problem, not solved it.
# ---------------------------------------------------------------------------

# TOKEN is deliberately ABSENT from the credential words, and its
# absence is load-bearing rather than an oversight. This codebase counts
# tokens everywhere -- `max_tokens=`, `prompt_tokens=`, `context_tokens=`,
# `completion_tokens=`, `token_budget=` -- and including it produced 24
# findings in one run, none of them a credential. A check that reports
# two dozen false positives is a check people learn to override, which
# is worse than not having it. The token-shaped names that ARE
# credentials are named explicitly instead.
_SECRET_ASSIGNMENT_RE = re.compile(
    r"""(?P<name>[A-Za-z0-9_]*
        (?:API_?KEY|SECRET|PASSWORD|PASSWD|CREDENTIAL
           |ACCESS_?TOKEN|AUTH_?TOKEN|BEARER_?TOKEN|REFRESH_?TOKEN)
        [A-Za-z0-9_]*)
        \s*[:=]\s*
        (?P<quote>["']?)(?P<value>[^\s"'#,;]{16,})(?P=quote)""",
    re.IGNORECASE | re.VERBOSE)

# A value that is CODE, not a literal. `password=settings.opensearch_password`
# is a reference; `secret_key=build(...)` is a call. Neither can leak
# anything, and both are ordinary in a codebase that passes credentials
# around by name -- which is exactly the pattern good code uses, so
# flagging it would penalise the right thing.
# THREE SHAPES, NOT ONE, and the narrowing is a defect this check
# already had. A first version matched any identifier-shaped value --
# `^[A-Za-z_][A-Za-z0-9_]*$` -- which is also the shape of a real API
# key: a provider key is letters and digits with no
# punctuation, so it parsed as "a variable name" and a planted 32-char
# Mistral-shaped key packaged cleanly. Caught by testing the check
# against a leak rather than only against the tree it was written on.
#
#   a call            build_client(...)              -> has "("
#   an attribute path settings.opensearch_password   -> has "."
#   a bare local      opensearch_password            -> snake_case, and
#                                                       MUST contain "_"
#
# The underscore requirement is what separates a Python name from a key.
# Provider keys do not carry underscores; local variables holding
# credentials in this codebase invariably do (`api_key`, `secret_key`,
# `opensearch_password`). A single-word lowercase value like `hunter2`
# is therefore still scanned, which is correct.
_CALL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*\s*\(")
_ATTRIBUTE_PATH_RE = re.compile(
    r"^[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)+$")
_SNAKE_LOCAL_RE = re.compile(r"^[a-z_][a-z0-9_]*_[a-z0-9_]*$")

# A DSN with an inline password: postgresql://user:pass@host/db
_DSN_WITH_PASSWORD_RE = re.compile(
    r"[a-z][a-z0-9+.-]*://(?P<user>[^\s:/@]+):(?P<pw>[^\s:/@]{3,})@",
    re.IGNORECASE)

# Values that are obviously not credentials. Substring match, lowercased.
# Deliberately generous: a false NEGATIVE here costs the backstop's help
# on one line, while a false POSITIVE blocks a release over a docstring
# and teaches people to pass --allow-suspect reflexively, which is worse.
_PLACEHOLDER_MARKERS = (
    "your-", "your_", "<your", "xxx", "changeme", "change-me", "replace",
    "example", "placeholder", "not-needed", "dummy", "fake", "sample",
    "todo", "n/a", "none", "null", "redacted", "...", "abc123",
    "sk-...", "pk-...", "insert", "here",
    # Documentation's stand-in credentials. `user:pass@host` appears in
    # internal/DDGS_GUIDE.md and internal/GLOSSARY.md as the SHAPE of a
    # connection string, which is exactly the thing a runbook should
    # show, and "pick-something-long-and-random" is OPERATIONS.md telling
    # a reader what to choose. Both are the check working correctly on
    # the wrong side: the shape is what makes them findable, and the
    # value is what makes them harmless.
    "pick-", "random", "secret-goes",
)

# Usernames that are obviously the WORD "user" rather than an account.
# A tiny explicit set, NOT _looks_like_placeholder: that function's
# prose rule treats any all-letters value as a stand-in, and a real
# username is all letters -- running it on this field silently disarmed
# the DSN check for every genuine connection string. Caught by
# test_a_dsn_with_a_real_password_is_caught, which is the reason to
# write a test that asserts the check FIRES and not only that it stays
# quiet.
_STANDIN_USERNAMES = frozenset({
    "user", "username", "youruser", "your-user", "your_user", "myuser",
    "someuser", "dbuser",
})

# A hyphenated or underscored ENGLISH PHRASE, with no digits anywhere.
# `PROPRIETARY-CORPUS-SENTENCE` (a test fixture) and
# `pick-something-long-and-random` (OPERATIONS.md's advice) are both this
# shape; a real key from any provider observed here is not, because
# every one of them mixes digits in.
#
# THE TRADE-OFF, stated rather than buried: a genuinely digit-free
# passphrase would be missed. That is the correct direction for a
# BACKSTOP to fail -- the exclude list is what actually keeps secrets
# out, and a scan that blocks a release over a test fixture is a scan
# that gets overridden by habit, at which point it protects nothing.
_PROSE_VALUE_RE = re.compile(r"^[A-Za-z][A-Za-z_-]*$")

# Files whose whole job is to SHOW these shapes. Their placeholder values
# already pass the marker test above; this makes the intent explicit so a
# future edit that adds a realistic-looking example does not silently
# start failing releases.
# package.py exempts ITSELF, and that is not special pleading: this file
# DEFINES the credential patterns, so its own regex sources and the
# worked examples in its comments match them by construction. A scanner
# that fails on its own rule table can never pass, and a check that can
# never pass is one nobody reads.
# test_ops_package.py is exempt for the same reason and needs the same
# defence: its fixtures are deliberately realistic keys, because a test
# built from obvious placeholders would exercise the placeholder path
# and prove nothing about the one that matters. A guard whose own test
# suite cannot ship is not shippable.
_SCAN_EXEMPT = (".env.example", "package.py", "test_ops_package.py")


def _looks_like_placeholder(value: str) -> bool:
    lowered = value.lower()
    if any(marker in lowered for marker in _PLACEHOLDER_MARKERS):
        return True
    if _PROSE_VALUE_RE.match(value):
        return True
    # A run of one repeated character, or an obviously fake literal.
    return len(set(lowered)) <= 2


def _is_reference_not_literal(value: str) -> bool:
    """True when the value is a name or a call rather than a secret.

    See the three regexes above for why this is deliberately narrower
    than "looks like an identifier" -- that broader rule let a planted
    32-character API key through, because a key is identifier-shaped.
    """
    candidate = value.strip().strip("`")
    return bool(_CALL_RE.match(candidate)
                or _ATTRIBUTE_PATH_RE.match(candidate)
                or _SNAKE_LOCAL_RE.match(candidate))


def _is_demo_credential(user: str, password: str) -> bool:
    """`agent:agent`, `admin:admin`, `postgres:postgres` -- a DSN whose
    password IS its username is a documented sample, not a secret.

    This repo ships exactly that as its default DSN
    (`postgresql://agent:agent@localhost:5432/agent`, config.py) and
    prints it in OPERATIONS.md twice, so without this rule the check
    fails on its own documentation forever -- and a check that always
    fails teaches people to pass --allow-suspect without reading it.
    """
    return user.lower() == password.lower()


def scan_text(text: str, relpath: str) -> list:
    """Credential-shaped values in one file. Pure; returns findings.

    RETURNS [(line_number, name, why), ...] -- never the value itself.

    CALLED BY   build(), for every file about to enter the archive whose
                content is decodable as UTF-8. A binary file is not
                scanned and says so in the summary rather than being
                silently treated as clean.

    WHAT IT CANNOT SEE, stated so nobody mistakes a pass for a guarantee:
    a credential that is not written as an assignment, one shorter than
    16 characters, one inside a binary or an archive, and one that
    happens to contain a placeholder marker. It is the last line of
    defence behind the exclude list, not a substitute for it.
    """
    if pathlib.PurePosixPath(relpath).name in _SCAN_EXEMPT:
        return []
    findings = []
    for number, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped:
            continue
        for match in _SECRET_ASSIGNMENT_RE.finditer(line):
            value = match.group("value")
            if _looks_like_placeholder(value) or _is_reference_not_literal(value):
                continue
            findings.append((number, match.group("name"),
                             f"a {len(value)}-character value assigned to a "
                             f"credential-shaped name"))
        dsn = _DSN_WITH_PASSWORD_RE.search(line)
        if (dsn and not _looks_like_placeholder(dsn.group("pw"))
                and dsn.group("user").lower() not in _STANDIN_USERNAMES
                and not _is_demo_credential(dsn.group("user"),
                                            dsn.group("pw"))):
            findings.append((number, "connection string",
                             "a URL carrying an inline password"))
    return findings


def is_excluded(relpath: str) -> bool:
    """Should this path stay out of the archive? Pure.

    `relpath` is POSIX-style and relative to the repo root. Every path
    SEGMENT is tested, not just the final name, so `src/x/__pycache__/y.pyc`
    is excluded by the `__pycache__` directory rule rather than needing a
    pattern that anticipates its depth.
    """
    parts = pathlib.PurePosixPath(relpath).parts
    if parts and parts[-1] in KEEP_ANYWAY:
        return False
    for pattern in EXCLUDE_PATTERNS:
        if pattern.startswith("!"):
            continue                      # negations live in KEEP_ANYWAY
        for part in parts:
            if fnmatch.fnmatch(part, pattern):
                return True
    return False


def collect(root: pathlib.Path) -> tuple:
    """Walk `root` and split it into (included, excluded) relative paths.

    Both lists are sorted, so a dry run is diffable against the previous
    one -- the cheapest way to notice that a new directory started
    shipping, or stopped.
    """
    included, excluded = [], []
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = pathlib.Path(dirpath).relative_to(root).as_posix()
        rel_dir = "" if rel_dir == "." else rel_dir
        # Prune excluded directories in place, so os.walk does not descend
        # into a .venv with 30,000 files in it just to reject them one by
        # one. This is what keeps a dry run instant.
        kept = []
        for name in dirnames:
            rel = f"{rel_dir}/{name}" if rel_dir else name
            if is_excluded(rel):
                excluded.append(rel + "/")
            else:
                kept.append(name)
        dirnames[:] = kept
        for name in sorted(filenames):
            rel = f"{rel_dir}/{name}" if rel_dir else name
            (excluded if is_excluded(rel) else included).append(rel)
    return sorted(included), sorted(excluded)


def verify_archive(zip_path: pathlib.Path) -> list:
    """Re-open the WRITTEN file and report any forbidden entry.

    CALLED BY   build(), after the archive is closed -- deliberately
                against the artifact rather than against the list that
                produced it. Checking the list would only prove the list
                agrees with itself; this proves the bytes on disk are
                what the policy says they should be, which is the claim
                actually being made to a reviewer.

    This is `unzip -l research-agent.zip | grep -i "\\.env$"` from
    README's Packaging section, made non-optional and cross-platform.
    """
    offenders = []
    with zipfile.ZipFile(zip_path) as archive:
        for name in archive.namelist():
            # Entries carry a top-level directory prefix; drop it before
            # applying the same policy the walk used.
            inner = name.split("/", 1)[1] if "/" in name else name
            if inner and is_excluded(inner):
                offenders.append(name)
    return offenders


def build(root: pathlib.Path, out: pathlib.Path, prefix: str,
          allow_suspect: bool = False) -> tuple:
    """Write the archive and verify it. Returns (included, findings).

    Writes to a TEMPORARY name and renames on success, so a refused
    build never leaves a half-written zip that someone could pick up and
    send. A failed verification deletes the file outright rather than
    leaving it for a `--force` that does not exist: there is no
    legitimate reason to ship an archive this command has just said is
    unsafe.
    """
    included, _ = collect(root)
    findings = []
    for rel in included:
        path = root / rel
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue                      # binary or unreadable; not scanned
        for number, name, why in scan_text(text, rel):
            findings.append((rel, number, name, why))
    if findings and not allow_suspect:
        return included, findings

    out.parent.mkdir(parents=True, exist_ok=True)
    staging = out.with_suffix(out.suffix + ".partial")
    with zipfile.ZipFile(staging, "w", zipfile.ZIP_DEFLATED) as archive:
        for rel in included:
            archive.write(root / rel, arcname=f"{prefix}/{rel}")
    offenders = verify_archive(staging)
    if offenders:
        staging.unlink()
        raise RuntimeError(
            "the archive contained forbidden paths after being written, "
            "which means EXCLUDE_PATTERNS and the walk disagree: "
            + ", ".join(offenders[:10]))
    if out.exists():
        out.unlink()
    staging.rename(out)
    return included, findings


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Build the distributable archive from an explicit "
                    "exclude list, then verify the file that was written.")
    parser.add_argument("--out", default=None,
                        help="output path (default: ../research-agent.zip, "
                             "i.e. beside the checkout rather than inside "
                             "it, so a second run cannot package the first)")
    parser.add_argument("--prefix", default=None,
                        help="top-level directory inside the archive "
                             "(default: the checkout's own directory name)")
    parser.add_argument("--dry-run", action="store_true",
                        help="list what would be included; write nothing")
    parser.add_argument("--list-excluded", action="store_true",
                        help="with --dry-run, also list what is being left "
                             "out and why it matters")
    parser.add_argument("--allow-suspect", action="store_true",
                        help="package anyway despite credential-shaped "
                             "findings. For a false positive ONLY -- if a "
                             "finding is real, the remedy is to remove the "
                             "value AND rotate it, because a smaller zip "
                             "does not un-send one already shared")
    args = parser.parse_args(argv)

    if REPO_ROOT is None:
        print("research-agent-package needs a checkout: it archives this "
              "repository's working tree, and an installed package is not "
              "one. Run it from a clone.", file=sys.stderr)
        return 2

    prefix = args.prefix or REPO_ROOT.name
    out = pathlib.Path(args.out) if args.out else \
        REPO_ROOT.parent / f"{prefix}.zip"

    if args.dry_run:
        included, excluded = collect(REPO_ROOT)
        print(f"{len(included)} file(s) would be archived as {prefix}/")
        for rel in included:
            print(f"  + {rel}")
        if args.list_excluded:
            print(f"\n{len(excluded)} path(s) excluded:")
            for rel in excluded:
                print(f"  - {rel}")
        print("\n(nothing was written; drop --dry-run to build)")
        return 0

    try:
        included, findings = build(REPO_ROOT, out, prefix,
                                   allow_suspect=args.allow_suspect)
    except RuntimeError as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 1

    if findings and not args.allow_suspect:
        print("REFUSED: credential-shaped values found in files that would "
              "have been archived.\n", file=sys.stderr)
        for rel, number, name, why in findings:
            print(f"  {rel}:{number}  {name} -- {why}", file=sys.stderr)
        print("\nThe value itself is deliberately not printed. If any of "
              "these is real:\n"
              "  1. remove it from the file;\n"
              "  2. ROTATE it -- assume it is already public;\n"
              "  3. re-run this command.\n"
              "If every one is a false positive, --allow-suspect packages "
              "anyway.", file=sys.stderr)
        return 1

    size_mb = out.stat().st_size / (1024 * 1024)
    print(f"Wrote {out}  ({len(included)} files, {size_mb:.1f} MB)")
    print("Verified: no excluded path is present in the archive.")
    if findings:
        print(f"NOTE: {len(findings)} credential-shaped finding(s) were "
              f"overridden with --allow-suspect.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
